# Go — toolchain configuration, and the PATH entry that goes with it.
#
# WHAT THIS REPLACES. Go configuration was previously smeared across four
# hand-written shell files:
#
#   config/fish/conf.d/10-env.fish    set -gx GOFLAGS -buildvcs=false
#   config/bash/bashrc.d/10-env.sh    export GOFLAGS=-buildvcs=false
#   config/fish/conf.d/30-path.fish   fish_add_path -gmp (go env GOPATH)/bin
#   config/bash/bashrc.d/30-path.sh   path_prepend "$(go env GOPATH)/bin"
#
# Two problems with that, both now fixed:
#
#   1. `go env GOPATH` SPAWNS A PROCESS AT EVERY SHELL START (measured 2ms).
#      GOPATH is a constant; it does not need to be discovered by executing the
#      go toolchain. It is declared below and interpolated into the shell
#      fragments at build time.
#
#   2. GOFLAGS as a shell variable only applies to shells. Declared through
#      programs.go it lands in ~/.config/go/env, which the go tool itself reads
#      — so it also applies to Rider, to editor LSPs, and to anything else that
#      invokes go without a login shell.
#
# ---------------------------------------------------------------------------
# A CONFLICT THIS UNCOVERED — READ BEFORE CHANGING GOFLAGS
# ---------------------------------------------------------------------------
# ~/.config/go/env already existed on gluck, containing:
#
#     GOFLAGS=-mod=mod
#
# while the shell exported GOFLAGS=-buildvcs=false. An environment variable
# BEATS the go env file, so `go env GOFLAGS` reported -buildvcs=false and
# `-mod=mod` has been silently dead for however long both have existed.
#
# Only -buildvcs=false is declared below, which PRESERVES the behaviour you
# actually have today. If -mod=mod was wanted, the value is space-separated:
#
#     GOFLAGS = "-buildvcs=false -mod=mod";
#
# It is deliberately not enabled here: reinstating a flag that has been inert
# would change how every go build resolves modules, and that is a decision, not
# a migration.
#
# home-manager now owns ~/.config/go/env, so the existing file collides on the
# first switch and needs `-b bak` like the others.
{
  flake.modules.homeManager.go =
    {
      config,
      lib,
      pkgs,
      ...
    }:
    let
      goPath = "${config.home.homeDirectory}/go";
    in
    {
      programs.go = {
        enable = true;

        # The distro owns the toolchain unless the host says otherwise — the
        # same rule as gcc/node in editor.nix. `package = null` is exactly the
        # nullable-package idiom: take the CONFIGURATION management, leave the
        # binary to pacman. See docs/pacman-audit.md.
        package = lib.mkIf (!config.my.platform.toolchainFromNix) null;

        env = {
          GOPATH = goPath;
          GOFLAGS = "-buildvcs=false";
        };
      };

      # ----------------------------------------------------------------------
      # PATH — and the ordering is load-bearing.
      # ----------------------------------------------------------------------
      # These fragments are numbered 25, BEFORE 30-path. That is deliberate:
      # both shells PREPEND, so whatever is added first ends up LAST. Adding
      # $GOPATH/bin at 25 leaves it behind ~/.nix-profile/bin, ~/.local/bin,
      # ~/.cargo/bin and ~/.bun/bin — which is where it was, and must stay.
      #
      # WHY IT MATTERS: ~/go/bin contains `fig` (and `dio`, `figwal`) from
      # `go install`. If this ran after 30-path it would sit in FRONT of
      # ~/.nix-profile/bin and shadow the nix-installed figaro with whatever
      # stale binary `go install` last left there. Silent, and confusing.
      #
      # No dependency on 30-path's path_prepend helper, which is not defined
      # yet at this point — each fragment does its own idempotent insert.
      xdg.configFile."fish/conf.d/25-go.fish".text = ''
        # Generated by modules/go.nix. GOPATH is declared in nix, not discovered
        # by running `go env GOPATH` at every shell start.
        #
        # Runs BEFORE 30-path so $GOPATH/bin ends up BEHIND the nix profile —
        # ~/go/bin holds `go install` output including fig, which must not
        # shadow the nix figaro.
        if not set -q IN_NIX_SHELL
            fish_add_path -gmp ${goPath}/bin
        end
      '';

      home.file.".bashrc.d/25-go.sh".text = ''
        # Generated by modules/go.nix. See the fish twin, 25-go.fish.
        #
        # Idempotent by hand: path_prepend is defined in 30-path.sh, which has
        # not been sourced yet.
        if [ -z "$IN_NIX_SHELL" ]; then
            case ":$PATH:" in
                *":${goPath}/bin:"*) : ;;
                *) PATH="${goPath}/bin''${PATH:+:$PATH}"; export PATH ;;
            esac
        fi
      '';
    };
}
