# Zen browser: prefs, extensions, shortcuts. Not the binary.
#
# Opt-in aspect (named in a host's `roles`), because it writes a live browser
# profile. Both hosts run zen-browser-bin from pacman and nixpkgs has no
# zen-browser at all, so `package` is null everywhere. Consequence: `policies`
# never apply (they live in a wrapper we don't build), so extensions install as
# xpi files dropped into the profile instead.
#
# Not owned here: settings inside an extension, e.g. Vimium C's keymap. Those
# live in the extension's IndexedDB and home-manager's route to them
# (extensions.settings) forces the whole profile to the legacy storage backend,
# hiding what every other extension stored (home-manager#9211). Use the
# extension's own export/import.
{ inputs, ... }:
{
  flake.modules.homeManager.zen =
    {
      config,
      lib,
      pkgs,
      ...
    }:
    let
      addons = inputs.firefox-addons.packages.${pkgs.stdenv.hostPlatform.system};

      # Generated by bin/zen-shortcuts-export; read its header before editing.
      shortcuts = builtins.fromJSON (builtins.readFile ../../config/zen/keyboard-shortcuts.json);
    in
    {
      imports = [ inputs.zen-browser.homeModules.beta ];

      options.my.zen = {
        configPath = lib.mkOption {
          type = lib.types.str;
          default = ".zen";
          example = ".config/zen";
          description = ''
            Directory under $HOME that this machine's Zen reads. `.zen` on older
            installs, `.config/zen` on newer ones; check which exists. A wrong
            value does not error, it configures a profile the browser never
            opens.
          '';
        };

        profileDir = lib.mkOption {
          type = lib.types.str;
          default = "default";
          example = "829beuvl.Default (release)";
          description = ''
            Profile directory inside `configPath`. Zen generates a random
            prefix on first run, so read the real name out of profiles.ini
            rather than inventing one. Same failure mode as configPath: silent.
          '';
        };

        shortcutsVersion = lib.mkOption {
          type = lib.types.nullOr lib.types.int;
          default = shortcuts.version;
          defaultText = lib.literalExpression "the version recorded in config/zen/keyboard-shortcuts.json";
          description = ''
            Schema version this machine's Zen speaks, from about:config's
            `zen.keyboard.shortcuts.version`. Activation refuses to patch on a
            mismatch. Defaults to the version the export was taken at; a host
            whose Zen lags names its own until it catches up.
          '';
        };
      };

      config = {
        # profiles.ini is a registry the browser maintains, not configuration.
        # Since Firefox 67 an install claims its profile through an
        # [InstallXXXXXXXX] section keyed by the install path; the generated
        # file has none, so Zen tries to write one, finds a store symlink, and
        # refuses to start ("profile cannot be loaded"). Measured 2026-09-06.
        home.file."${config.my.zen.configPath}/profiles.ini".enable = false;

        programs.zen-browser = {
          enable = true;

          # pacman owns anything that draws (see modules/platform.nix). mkIf on
          # the negated flag so a desktopFromNix host falls back to the upstream
          # default rather than a null we chose for it.
          package = lib.mkIf (!config.my.platform.desktopFromNix) null;

          # Upstream marks these internal; we set them because the binary is
          # not ours, so the paths are its, not the module's.
          configPath = config.my.zen.configPath;
          profilesPath = config.my.zen.configPath;

          profiles.default = {
            id = 0;
            isDefault = true;
            path = config.my.zen.profileDir;

            extensions = {
              # Required: these are already installed by hand in the profile.
              force = true;
              packages = [
                addons.vimium-c
                addons.ublock-origin
                addons.auto-tab-discard
                addons.don-t-fuck-with-paste

                # Not in rycee's set. See pkgs/firefox-xpi.nix.
                (pkgs.callPackage ../../pkgs/firefox-xpi.nix { } {
                  name = "kanagawa-wave-dark-theme";
                  version = "2.5";
                  addonId = "{7efc2a80-496f-49b1-88db-4ddd7d312757}";
                  url = "https://addons.mozilla.org/firefox/downloads/file/4847676/kanagawa_wave_dark_theme-2.5.xpi";
                  hash = "sha256-V9qf5D4sN6Xp7qrzUBKOlMNzhp4Eo0WsuF3JE3KCSVM=";
                })

                # rycee has this one, but it is unfree and their package is
                # evaluated in their own nixpkgs, which we cannot hand an
                # allowUnfree predicate. Pinned here so the license is declared
                # and modules/host-builder.nix can permit it by name.
                (pkgs.callPackage ../../pkgs/firefox-xpi.nix { } {
                  name = "1password-x-password-manager";
                  version = "8.12.32.33";
                  addonId = "{d634138d-c276-4fc8-924b-40a0ea21d284}";
                  url = "https://addons.mozilla.org/firefox/downloads/file/4951729/1password_x_password_manager-8.12.32.33.xpi";
                  hash = "sha256-uVL7YXAn94tWSf/diPWLwH2pLSHcc8xrtuKIeeXi4ws=";
                  license = lib.licenses.unfree;
                })
              ];
            };

            # Deliberate choices only. Zen writes plenty else into prefs.js
            # (migration flags, build ids, learned urlbar ranking) and that is
            # state, not configuration.
            settings = {
              # Without this the theme xpi is installed and inert.
              "extensions.activeThemeID" = "{7efc2a80-496f-49b1-88db-4ddd7d312757}";

              "zen.view.use-single-toolbar" = false;
              "zen.view.compact.enable-at-startup" = false;
              "zen.view.compact.should-enable-at-startup" = false;
              "zen.view.compact.hide-toolbar" = true;
              "zen.theme.gradient.show-custom-colors" = true;

              # Follow the system light/dark scheme.
              "zen.view.window.scheme" = 0;

              "browser.urlbar.suggest.quicksuggest.sponsored" = false;
            };

            # The tab-unloader block, kept as a file because its comments carry
            # the measurements.
            extraConfig = builtins.readFile ../../config/zen/user.js;

            # Patched by id at activation rather than replacing the file, so a
            # Zen release that adds shortcuts does not lose them. Close Zen
            # before switching: a running instance writes its copy back on exit.
            keyboardShortcuts = map (s: {
              inherit (s)
                id
                key
                keycode
                modifiers
                disabled
                ;
            }) shortcuts.shortcuts;

            keyboardShortcutsVersion = config.my.zen.shortcutsVersion;
          };
        };
      };
    };
}
